## Customize the test machine
machine:
  timezone:
    America/Los_Angeles # Set the timezone
## Customize dependencies
dependencies:
  override:
    - npm install
    # - npm install -g hexo
    - npm install -g hexo-cli
## Customize test commands
test:
 override:
   - echo "testing"
## Customize deployment commands
deployment:
  prod:
    branch: CircleCIIssue#2
    commands:
      - hexo clean
      - hexo generate
      - aws s3 sync public/ s3://www.demotestsite.net --region ca-central-1 --acl public-read
