version: 2
jobs:
  build:
    docker:
      - image: node:9.9.0-stretch
    working_directory: ~/demotestsite.net
    steps:
      - checkout
      - run:
          name: Install Hexo CLI
          command: npm install -g hexo-cli
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Generate static website
          command: hexo generate
#      - run:
#          name: Install AWS CLI
#          command: |
#            apt-get update
#            apt-get install -y awscli
      - run:
          name: Check python
          command: python --version
      - run:
          name: Pip
          command: apt-get install python-pip
      - run:
          name: Install AWS CLI
          command: pip install awscli
      - run:
          name: Push to S3 bucket
          command: cd public/ && aws s3 sync . s3://www.demotestsite.net --region ca-central-1 --acl public-read
