machine:
  timezone:
    America/Argentina/Buenos_Aires
dependencies:
  override:
    - npm install
    - npm install -g hexo-cli
test:
  override:
    - echo "testing"
deployment:
  prod:
    branch: CircleCIIssue#2
    commands:
      - hexo clean
      - hexo generate
      - aws s3 sync public/ s3://www.demotestsite.net --region ca-central-1 --acl public-read
